
server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roydon_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml # ???="classpath*:/mapper/**/*.xml"
